name: kemet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.1.1

  shared_preferences: ^2.2.3

  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  firebase_messaging: ^15.2.10
  firebase_storage: ^12.4.10
  cloud_firestore: ^5.6.12
  pinput: ^5.0.0
  url_launcher: ^6.3.1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/log11o.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "images/1024.png"

flutter_native_splash:
  color: "#131517"
  image: images/splash1.png

  android: true
  ios: true

  android_12:
    image: images/splash1.png
    color: "#131517"